var num1 = 1;
console.log("The First Number:", num1);
var num2 = 0.2;
console.log("The Second Number:", num2);
var num3 = -3;
console.log("The Third Number:", num3);
var num4 = -0.4;
console.log("The Fourth Number:", num4);
var string1 = "uno";
console.log("The First String:", string1);
var string2 = "ni";
console.log("The Second String:", string2);
var string3 = "three";
console.log("The Third String:", string3);
var bool1 = true;
console.log("The First Boolean:", bool1);
var bool2 = false;
console.log("The Second Boolean:", bool2);
var undef = undef;
console.log("Undefined:", undef);

